# Generated by Django 5.2.16 on 2026-08-05 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Наименование должности"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Максимум 6 символов. Например ОС-001",
                        max_length=6,
                        verbose_name="Код должности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "personal_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Табельный номер"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("vacation", "Отпуск"),
                            ("sick", "Больничный"),
                            ("fired", "Уволен"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата приема"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="employees.department",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="employees.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Сотрудник",),
                "verbose_name_plural": "Сотрудники",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="employees.employee",
                verbose_name="Руководитель",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=1,
                        verbose_name="Уровень владения",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык сотрудника",
                "verbose_name_plural": "Навыки сотрудников",
                "unique_together": {("employee", "skill")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="skill",
            field=models.ManyToManyField(
                related_name="employees",
                through="employees.EmployeeSkill",
                to="employees.skill",
                verbose_name="Навыки",
            ),
        ),
    ]
