# Generated by Django 5.2.16 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalposition",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("employee", "Сотрудник (только свои задачи)"),
                    ("master", "Мастер (задачи своего участка)"),
                    ("manager", "Менеджер (все заказы)"),
                    ("director", "Директор (все заказы + отчеты)"),
                    ("admin", "Администратор (полный доступ)"),
                ],
                default="employee",
                max_length=20,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("employee", "Сотрудник (только свои задачи)"),
                    ("master", "Мастер (задачи своего участка)"),
                    ("manager", "Менеджер (все заказы)"),
                    ("director", "Директор (все заказы + отчеты)"),
                    ("admin", "Администратор (полный доступ)"),
                ],
                default="employee",
                max_length=20,
                verbose_name="Уровень доступа",
            ),
        ),
    ]
