# Generated by Django 5.2.16 on 2026-08-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_historicalposition_access_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
