# Generated by Django 5.2.16 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="skill",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="employees",
                through="employees.EmployeeSkill",
                to="employees.skill",
                verbose_name="Навыки",
            ),
        ),
    ]
