# Generated by Django 5.2.16 on 2026-08-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalemployee",
            name="history_change_reason",
        ),
    ]
