# Generated by Django 5.2.16 on 2026-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_historicaldepartment_historicalemployee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="skill",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                through="employees.EmployeeSkill",
                to="employees.skill",
                verbose_name="Навыки",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalEmployeeSkill",
        ),
    ]
