# Generated by Django 5.2.16 on 2026-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_historicalemployeeskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalemployee",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
