# Generated by Django 5.2.16 on 2026-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_historicalemployee_history_change_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalskill",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Короткое обозначение для матрицы (например: Фрез, Ток, Свар)",
                max_length=20,
                verbose_name="Код навыка",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Короткое обозначение для матрицы (например: Фрез, Ток, Свар)",
                max_length=20,
                verbose_name="Код навыка",
            ),
        ),
    ]
