# Generated by Django 5.2.16 on 2026-08-12 12:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Краткое наименование"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ind_person", "Физическое лицо"),
                            ("legal", "Юридическое лицо"),
                            ("sole_pr", "ИП"),
                            ("self_emp", "Самозанятый"),
                        ],
                        default="legal",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                ("kpp", models.CharField(blank=True, max_length=9, verbose_name="КПП")),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контактное лицо"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Юридический адрес"),
                ),
                (
                    "actual_address",
                    models.TextField(blank=True, verbose_name="Фактический адрес"),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Банк"),
                ),
                ("bik", models.CharField(blank=True, max_length=9, verbose_name="БИК")),
                (
                    "checking_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Расчетный счет"
                    ),
                ),
                (
                    "cor_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Кор. счет"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCustomer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Краткое наименование"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ind_person", "Физическое лицо"),
                            ("legal", "Юридическое лицо"),
                            ("sole_pr", "ИП"),
                            ("self_emp", "Самозанятый"),
                        ],
                        default="legal",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                ("kpp", models.CharField(blank=True, max_length=9, verbose_name="КПП")),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контактное лицо"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Юридический адрес"),
                ),
                (
                    "actual_address",
                    models.TextField(blank=True, verbose_name="Фактический адрес"),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Банк"),
                ),
                ("bik", models.CharField(blank=True, max_length=9, verbose_name="БИК")),
                (
                    "checking_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Расчетный счет"
                    ),
                ),
                (
                    "cor_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Кор. счет"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата редактирования"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений",
                "verbose_name_plural": "historical customers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
