# Generated by Django 5.2.16 on 2026-08-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["name"],
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcustomer",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "История изменений",
                "verbose_name_plural": "historical Контрагенты",
            },
        ),
    ]
