# Generated by Django 5.2.16 on 2026-08-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="bnak_name",
            new_name="bank_name",
        ),
        migrations.RenameField(
            model_name="historicalcustomer",
            old_name="bnak_name",
            new_name="bank_name",
        ),
    ]
