# Generated by Django 5.2.16 on 2026-08-12 12:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "file",
                    models.FileField(
                        upload_to="drawings/%Y/%m/%d", verbose_name="Файл"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Версия"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_drawings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чертеж",
                "verbose_name_plural": "Чертежи",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование проекта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В работе"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Высокий"),
                            ("medium", "Средний"),
                            ("low", "Низкий"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "planned_completion_date",
                    models.DateField(verbose_name="Плановая дата сдачи"),
                ),
                (
                    "actual_complition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата сдачи"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Последние изменения"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="customers.customer",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений",
                "verbose_name_plural": "historical Заказы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrderFile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("file", models.TextField(max_length=100, verbose_name="Файл")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("contract", "Договор"),
                            ("specification", "Техническое задание"),
                            ("draw", "чертеж"),
                            ("estimate", "Смета"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата загрузки"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений",
                "verbose_name_plural": "historical Файлы заказов",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование проекта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В работе"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Высокий"),
                            ("medium", "Средний"),
                            ("low", "Низкий"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "planned_completion_date",
                    models.DateField(verbose_name="Плановая дата сдачи"),
                ),
                (
                    "actual_complition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата сдачи"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последние изменения"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "responsible_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalStage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер этапа")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Плановые часы"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Плановая дата начала"),
                ),
                (
                    "planned_finish_date",
                    models.DateField(verbose_name="Плановая дата завершения"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает назначения"),
                            ("assigned", "Назначен"),
                            ("in_progress", "В работе"),
                            ("completed", "Выполнен"),
                            ("defect", "Брак"),
                            ("problem", "Проблема"),
                            ("on_hold", "Приостановлен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактические часы",
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата начала"
                    ),
                ),
                (
                    "actual_finish_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Фактическая дата завершения",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата изменения"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="Назначеный сотрудник",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.department",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_skill",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.skill",
                        verbose_name="Требуемый навык",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений",
                "verbose_name_plural": "historical Этапы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "file",
                    models.FileField(upload_to="orders/%Y/%m/%d", verbose_name="Файл"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("contract", "Договор"),
                            ("specification", "Техническое задание"),
                            ("draw", "чертеж"),
                            ("estimate", "Смета"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_order_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл заказа",
                "verbose_name_plural": "Файлы заказов",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                related_name="orders",
                to="orders.orderfile",
                verbose_name="Файлы заказа",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер этапа")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Плановые часы"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Плановая дата начала"),
                ),
                (
                    "planned_finish_date",
                    models.DateField(verbose_name="Плановая дата завершения"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает назначения"),
                            ("assigned", "Назначен"),
                            ("in_progress", "В работе"),
                            ("completed", "Выполнен"),
                            ("defect", "Брак"),
                            ("problem", "Проблема"),
                            ("on_hold", "Приостановлен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактические часы",
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата начала"
                    ),
                ),
                (
                    "actual_finish_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Фактическая дата завершения",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_stages",
                        to="employees.employee",
                        verbose_name="Назначеный сотрудник",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stages",
                        to="employees.department",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stages",
                        to="orders.drawing",
                        verbose_name="Чертежи",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "required_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stages",
                        to="employees.skill",
                        verbose_name="Требуемый навык",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап",
                "verbose_name_plural": "Этапы",
                "ordering": ["order", "number"],
                "unique_together": {("order", "number")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalDrawing",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("file", models.TextField(max_length=100, verbose_name="Файл")),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Версия"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата загрузки"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.stage",
                        verbose_name="Файл к этапу...",
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений",
                "verbose_name_plural": "historical Чертежи",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="drawing",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawings",
                to="orders.stage",
                verbose_name="Файл к этапу...",
            ),
        ),
    ]
