# Generated by Django 5.2.16 on 2026-08-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalorder",
            old_name="actual_complition_date",
            new_name="actual_completion_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="actual_complition_date",
            new_name="actual_completion_date",
        ),
    ]
