# Generated by Django 5.2.16 on 2026-08-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_historicalorder_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorderfile",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия файла"),
        ),
        migrations.AddField(
            model_name="orderfile",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия файла"),
        ),
    ]
